footer:
  copyright: "© 2026 Constant Wave. Todos los derechos reservados."
  links:
    privacy_policy: "Política de Privacidad"
    terms_of_service: "Términos de Servicio"

header:
  links:
    games: "Juegos"
    team: "Equipo"
    contact: "Contacto y Soporte"

game:
  screenshots: "Así es como se ve el juego"
  stores: "Descárgalo ahora en las tiendas"
  more_games: "Más Juegos"
