footer:
  copyright: "© 2026 Constant Wave. All rights reserved."
  links:
    privacy_policy: "Privacy Policy"
    terms_of_service: "Terms of Service"

header:
  links:
    games: "Games"
    team: "Team"
    research: "Research"
    contact: "Contact & Support"

game:
  screenshots: "This is how the game looks like"
  stores: "Download now on the stores"
  soundcloud: "Listen on SoundCloud"
  more_games: "More Games"
